# Generated by Django 5.0.2 on 2024-02-13 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appGestion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='noteAttribuer',
            new_name='note',
        ),
    ]
