# Generated by Django 5.0.2 on 2024-02-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGestion', '0003_alter_note_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='DateNaissance',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
